name: Epic Template For SRE Project Work
description: A template to use when creating an Epic type of issue.
title: "[Epic]: "
labels: ["Epic", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Epic Issue Description
      description: Please enter the detailed description of the high level issue including answering what we are solving, why we are solving it and any contstraints.
      placeholder: "Description here please."
      value: "Description here please."
    validations:
      required: true
  - type: textarea
    id: epic-tasks
    attributes:
      label: Tasks
      description: List the tasks belonging to this epic by referencing the task (e.g. #480)
      placeholder: "- [ ] New Task"
      value: "- [ ] New Task"
